### ISSUE TITLE
Source the data and perform Data preprocessing

### ISSUE THREAD

**Issue by samuelchrista** [TeamEpicProjects/Predictive-Analytics-for-Sports#2]

**Comment by theanshulranade** [comment]
Data preprocessing performed.
Temporary dataframe created for specific purposes.

**Comment by PraiseTheErdtree** [comment]
Data sourced from kaggle. 
features were studied.
preliminary exploratory data analysis performed including line graphs, scatter plots

**Comment by Sairam-00** [comment]
Data preprocessing is done, and EDA is performed on the dataset.
