### ISSUE TITLE
Identify variables and perform EDA

### ISSUE THREAD

**Issue by samuelchrista** [TeamEpicProjects/Predictive-Analytics-for-Sports#5]

**Comment by theanshulranade** [comment]
Statistical Analysis performed for all-time data.
Performance Analysis for all-time data.
Statistical Analysis for last 3 seasons.

**Comment by PraiseTheErdtree** [comment]
In depth batter analysis was performed by slicing overs into powerplay, middle overs and death overs. 
The KPIs discussed were used to sort data. 
runs and wickets were plotted against the innings progression to observe trends
